services:
  web:
    build: .
    ports:
      - "5000:8000"
    networks:
      - web-tier
      - db-tier
      - redis-tier
    environment:
      - DJANGO_SETTINGS_MODULE=scrappy.settings
    volumes:
      - ./scrappy:/code/scrappy

  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=scrappyDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - "5432:5432"
    networks:
      - db-tier

  redis:
    image: redis:alpine
    networks:
      - redis-tier

networks:
  web-tier: {}
  db-tier: {}
  redis-tier: {}