services:
  web:
    build: .
    ports:
      - "5000:8000"
    networks:
      - web-tier
      - db-tier
      - redis-tier

    volumes:
      - ./scrappy:/code/scrappy

  database:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    networks:
      - db-tier

  redis:
    image: redis:alpine
    networks:
      - redis-tier

networks:
  web-tier: {}
  db-tier: {}
  redis-tier: {}