# Generated by Django 4.1.7 on 2023-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='death_year',
            field=models.IntegerField(null=True),
        ),
    ]
